### ISSUE TITLE
question

### ISSUE THREAD

**Issue by r-lyeh-archived** [memononen/milligui#1]
i built the sample a couple of days ago, with some minor troubles (as usual xD)
then i was surprised because of the new look & feel of this.
my question, is this going to look & feel like the nanovg demo instead? : )

**Comment by memononen** [comment]
The plan is to keep it pretty bare bones, utilitarian and flat (and hopefully fast). Once I get the basic structure set up, I hope I can slit up the visual styling a bit and maybe allow different backends too (i.e. if you just want to use 9-slices for everything).

I'm currently mostly trying to get the layouting and component composition stuff right; scroll bars, progress bars, popup windows, text inputs, shortcuts, reorderable lists, drag and drop, you name it :)

**Comment by r-lyeh-archived** [comment]
oops! left this open sorry O:)
ok good to know about the plans for this, good luck dude :D
